sudo: required
services:
        - docker
before_install:
        - docker build -t nat_077/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true nat_077/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: "eu-west-2"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-eu-west-2-049034683859"
        bucket_path: "docker-react"
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        on:
                branch: master


